spring:
  application:
    name: reviews


  # Enabling h2 console, accessible at http://localhost:8080/h2-console (use JDBC URL: jdbc:h2:mem:testdb, user: sa, password: empty (leave blank))
  h2:
    console:
      enabled: true

  datasource:
    url: "jdbc:h2:mem:testdb"
    username: "sa"
    password: ""
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false

logging:
  level:
    ROOT: INFO
    org.hibernate.stat: INFO
    org.hibernate.type: INFO

server:
  port: 8080

management:
  server:
    port: 8090
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    health:
      enabled: true
