spring:
  application:
    name: gateway

zuul:
  routes:
    webapi:
      sensitiveHeaders: Cookie,Set-Cookie,Authorization
      stripPrefix: false

eureka:
  client:
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 20202

logging:
  level:
    org.springframework.security.web: info
