@startuml

skinparam shadowing false

frame localhost {

    agent client <<localhost:20202>> as gatewayclient
    agent client <<localhost:7777>> as csclient
    agent client <<localhost:8761>> as sdsclient
    agent client <<localhost:9411>> as zipclient

    rectangle Docker {

        node config-server <<364a23e:8080>> as cs {
        }
        node service-discovery-server <<987f02a:8080>> as sds {
        }
        node gateway <<274d57d:8080>> as gateway {
        }
        node webapi <<165a66c:8080>> as webapi {
        }
        node items-service <<427b75d:8080>> as is {
        }
        node reviews-service <<544e99d:8080>> as rs {
        }
        node zipkin <<865f66b:9411>> as zipkin {
        }

        interface 20202 as gateport
        interface 7777 as csport
        interface 8761 as sdsport
        interface 9411 as zipport

        gateway - gateport
        zipkin -left- zipport

        cs - csport
        cs <~ gateway
        cs <~ webapi
        cs <~ is
        cs <~ rs
        cs <~ sds

        sds - sdsport
        sds <~ gateway
        sds <~ webapi
        sds <~ is
        sds <~ rs

        gateway --> webapi
        webapi --> is
        webapi --> rs

        gateway ~> zipkin
        webapi ~> zipkin
        is ~> zipkin
        rs ~> zipkin

        note top of cs : ip:172.67.0.3
        note top of sds : ip:172.67.0.4
        note top of gateway : ip:172.67.0.5
        note bottom of is : ip:172.67.0.6
        note bottom of rs : ip:172.67.0.7
        note bottom of zipkin : ip:172.67.0.8
        note left of webapi : ip:172.67.0.9
    }

    gatewayclient -up-> gateport
    csclient --> csport
    sdsclient -left-> sdsport
    zipclient -up-> zipport
}

@enduml