@startuml

skinparam shadowing false

frame localhost {

    component config-server <<localhost:7777>> as cs {
    }
    component service-discovery-server <<localhost:8761>> as sds {
    }
    component gateway <<localhost:20202>> as gateway {
    }
    component webapi <<localhost:8100>> as webapi {
    }
    component items-service <<localhost:8080>> as is {
    }
    component reviews-service <<localhost:9090>> as rs {
    }
    component zipkin <<localhost:9411>> as zipkin {
    }

    cs <~ gateway
    cs <~ webapi
    cs <~ is
    cs <~ rs
    cs <~ sds

    sds <~ gateway
    sds <~ webapi
    sds <~ is
    sds <~ rs

    gateway --> webapi
    webapi --> is
    webapi --> rs

    webapi ~> zipkin
    is ~> zipkin
    rs ~> zipkin
}

@enduml