zuul:
  routes:
    webapi:
      sensitiveHeaders: Cookie,Set-Cookie,Authorization
      stripPrefix: false

eureka:
  client:
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.security.web: info

spring:
  zipkin:
    base-url: http://localhost:9411


