spring:
  zipkin:
    base-url: http://localhost:9411

  # Enabling h2 console, accessible at http://localhost:8080/h2-console (use JDBC URL: jdbc:h2:mem:testdb, user: sa, password: empty (leave blank))
  h2:
    console:
      enabled: true
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false

logging:
  file: /tmp/codingsession/logs/items-service.log
  level:
    ROOT: INFO
    org.hibernate.stat: INFO
    org.hibernate.type: INFO
---
spring:
  profiles: docker

  zipkin:
    base-url: http://zipkin:9411

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-discovery-server:8761/eureka/
