spring:
  # Enabling h2 console, accessible at http://localhost:9090/h2-console (use JDBC URL: jdbc:h2:mem:testdb, user: sa, password: empty (leave blank))
  h2:
    console:
      enabled: true
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        generate_statistics: false

  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

logging:
  file: /tmp/codingsession/logs/reviews-service.log
  level:
    ROOT: INFO
    org.hibernate.stat: INFO
    org.hibernate.type: INFO

server:
  port: 9090

---
spring:
  profiles: docker

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-discovery-server:8761/eureka/