server:
  port: 8761

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
---
spring:
  profiles: docker

  zipkin:
    base-url: http://zipkin:9411

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-discovery-server:8761/eureka/