eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

spring:
  zipkin:
    base-url: http://localhost:9411

ribbon:
  ServerListRefreshInterval: 5000
  NFLoadBalancerPingInterval: 5

server:
  port: 8100

---
spring:
  profiles: docker

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-discovery-server:8761/eureka/