spring:
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka

ribbon:
  ServerListRefreshInterval: 5000
  NFLoadBalancerPingInterval: 5
---
spring:
  profiles: docker

  zipkin:
    base-url: http://zipkin:9411

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-discovery-server:8080/eureka/